# This is a basic workflow to help you get started with Actions

name: Push to coding

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: |
        npm install hexo-cli -g --silent
        npm install
        hexo cl
        hexo g

    - name: Push to gitee
      run: |
        git config --global user.email "i@dnocm.com"
        git config --global user.name "jiangtj"
        git clone https://${{ secrets.CODING_PASS }}@e.coding.net/jiangtj-lib/blog.git deploy_dir
        mv deploy_dir/.git public/.git
        cd public
        git add .
        git commit -m 'deploy: ${{ github.sha }}'
        git push -f https://${{ secrets.CODING_PASS }}@e.coding.net/jiangtj-lib/blog.git
