# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Push to gitee
      run: git push -f https://${{ secrets.GITEE_PASS }}@gitee.com/jiangtj/jiangtj.gitee.io.git

    - name: Setup Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build
      run: |
        npm install hexo-cli -g --silent
        npm install
        hexo g

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: master
        publish_dir: ./public
        external_repository: jiangtj/jiangtj.github.io
